# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift CI
on: [push, pull_request]

jobs:
  test:
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@v0
