#if !canImport(ObjectiveC)
import XCTest

extension AvroBinaryReaderTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AvroBinaryReaderTest = [
        ("testReadBoolean", testReadBoolean),
    ]
}

extension AvroDecodableTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AvroDecodableTest = [
        ("testArray", testArray),
        ("testBoolean", testBoolean),
        ("testBytes", testBytes),
        ("testDate", testDate),
        ("testDouble", testDouble),
        ("testDuration", testDuration),
        ("testEnum", testEnum),
        ("testField", testField),
        ("testFixed", testFixed),
        ("testFloat", testFloat),
        ("testInnerDuration", testInnerDuration),
        ("testInt", testInt),
        ("testLong", testLong),
        ("testMap", testMap),
        ("testNestedRecord", testNestedRecord),
        ("testPerformanceExample", testPerformanceExample),
        ("testRecord", testRecord),
        ("testString", testString),
        ("testUnion", testUnion),
        ("testUnionNull", testUnionNull),
    ]
}

extension AvroEnodableTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AvroEnodableTest = [
        ("testArray", testArray),
        ("testBoolean", testBoolean),
        ("testBytes", testBytes),
        ("testDate", testDate),
        ("testDouble", testDouble),
        ("testDuration", testDuration),
        ("testEnum", testEnum),
        ("testFixed", testFixed),
        ("testFloat", testFloat),
        ("testInnerDuration", testInnerDuration),
        ("testInt", testInt),
        ("testLong", testLong),
        ("testMap", testMap),
        ("testNestedRecord", testNestedRecord),
        ("testNestedRecordJson", testNestedRecordJson),
        ("testPerformanceExample", testPerformanceExample),
        ("testRecord", testRecord),
        ("testString", testString),
        ("testTime", testTime),
        ("testUnion", testUnion),
        ("testUnionNull", testUnionNull),
    ]
}

extension AvroSchemaCodingTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AvroSchemaCodingTest = [
        ("testArray", testArray),
        ("testBoolean", testBoolean),
        ("testBytes", testBytes),
        ("testDate", testDate),
        ("testDouble", testDouble),
        ("testDuration", testDuration),
        ("testEnum", testEnum),
        ("testFixed", testFixed),
        ("testFloat", testFloat),
        ("testInt", testInt),
        ("testLogicDecimalBytes", testLogicDecimalBytes),
        ("testLogicDecimalFixed", testLogicDecimalFixed),
        ("testLong", testLong),
        ("testMap", testMap),
        ("testMicrosecond", testMicrosecond),
        ("testMillisecond", testMillisecond),
        ("testNull", testNull),
        ("testPerformanceExample", testPerformanceExample),
        ("testRecord", testRecord),
        ("testString", testString),
        ("testTimestampMicro", testTimestampMicro),
        ("testTimestampMilli", testTimestampMilli),
        ("testUnion", testUnion),
    ]
}

extension AvroSchemaEquatableTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AvroSchemaEquatableTest = [
        ("testArray", testArray),
        ("testBoolean", testBoolean),
        ("testBytes", testBytes),
        ("testDouble", testDouble),
        ("testEnum", testEnum),
        ("testFixed", testFixed),
        ("testFloat", testFloat),
        ("testInt", testInt),
        ("testLong", testLong),
        ("testMap", testMap),
        ("testNull", testNull),
        ("testPerformanceExample", testPerformanceExample),
        ("testRecord", testRecord),
        ("testString", testString),
        ("testUnion", testUnion),
    ]
}

extension SwiftAvroCoreTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftAvroCoreTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AvroBinaryReaderTest.__allTests__AvroBinaryReaderTest),
        testCase(AvroDecodableTest.__allTests__AvroDecodableTest),
        testCase(AvroEnodableTest.__allTests__AvroEnodableTest),
        testCase(AvroSchemaCodingTest.__allTests__AvroSchemaCodingTest),
        testCase(AvroSchemaEquatableTest.__allTests__AvroSchemaEquatableTest),
        testCase(SwiftAvroCoreTests.__allTests__SwiftAvroCoreTests),
    ]
}
#endif
